In [5]:
# Importing supporting lib
import numpy as np

# Original matrix A before factorization
"""    [  4  12 -16]
       [ 12  37 -43]
       [-16 -43  98]
"""

# G and Gt were hand calculated
G = np.array([
     [2, 0, 0],
     [6, 1, 0],
     [-8, 5, 3]
])

Gt = np.array([
      [2, 6, -8],
      [0, 1, 5],
      [0, 0, 3]
])

# Calculaing matrix multiplication in order to check if hand factorization was calculated correctly
A = G @ Gt

# Checking result
A

array([[  4,  12, -16],
       [ 12,  37, -43],
       [-16, -43,  98]])

### End